steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/kubernetes-assignment-453414/kubernetes-repo/container1:${COMMIT_SHA}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/kubernetes-assignment-453414/kubernetes-repo/container1:${COMMIT_SHA}']

- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=./container1/
  - --location=us-central1-c
  - --cluster=kubernetes-assignment-cluster
  id: deploy

options:
  logging: CLOUD_LOGGING_ONLY